// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Revision.LINQ.Data;

#nullable disable

namespace Revision.LINQ.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Revision.LINQ.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Điện tử",
                            Name = "Laptop Dell XPS 13",
                            Price = 25000000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = "Điện tử",
                            Name = "iPhone 15 Pro Max",
                            Price = 30000000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            Category = "Điện tử",
                            Name = "Bàn phím cơ Keychron K2",
                            Price = 2500000m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 4,
                            Category = "Điện tử",
                            Name = "Chuột Logitech MX Master 3",
                            Price = 2000000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sách",
                            Name = "Sách: Clean Code",
                            Price = 250000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sách",
                            Name = "Sách: Design Patterns",
                            Price = 300000m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 7,
                            Category = "Điện tử",
                            Name = "Tai nghe Sony WH-1000XM5",
                            Price = 8000000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 8,
                            Category = "Điện tử",
                            Name = "Màn hình LG 27 inch 4K",
                            Price = 7500000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 9,
                            Category = "Điện tử",
                            Name = "Webcam Logitech C920",
                            Price = 1800000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 10,
                            Category = "Sách",
                            Name = "Sách: Refactoring",
                            Price = 280000m,
                            Stock = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
